import React from "react";
import { makeStyles } from "@material-ui/core/styles";
import texts from "../../utils/fontStyle"
import styles from "../../utils/styles";
import classnames from 'classnames'

const useStyles = makeStyles(styles);
const useTexts = makeStyles(texts);

export default function Section1() {

  const classes = useStyles();
  const texts = useTexts();

  return (
    <div className={classes.fluid}>
      <div>
        <div>
          <div className={classnames(texts.h007, texts.center)}>MOBILE APPLICATION TERMS AND CONDITIONS</div><p></p>
          <div className={classnames(texts.h007, texts.center)}>Deserts Software Pty Ltd</div><p></p>
          <div className={classnames(texts.center)}>Effective Date: 01/01/2018</div><p></p>
          <hr />
          <div>These terms and conditions (hereinafter "Terms") govern Your use of the following mobile application (which is hereinafter referred to as "the Product"): iTunes &amp; Goggle Play Store </div><p></p>
          <div>The Product is owned and operated by: Desert Software Pty Ltd (ACN 614728648) </div><p></p>
          <div>These Terms constitute a binding contract between You and: Desert Software Pty Ltd (ACN 614728648) </div><p></p>
          <div>In connection with Your use of the Product, we may also provide You with access to various other content, documentation, materials, information, goods or services. In these Terms, we refer to all of these items collectively as "the Items". </div><p></p>
          <div>These Terms will govern Your use of all pages of the Product, as well as Your use of the Items. </div><p></p>
          <div>If You continue to use the Product, You acknowledge that You have been given the chance to review the Terms. You acknowledge that You understand the Terms and that You agree to be bound by the Terms. </div><p></p>
          <div>If You do not understand the Terms, if You do not agree to be bound by the Terms, or if You need more time to review and consider the Terms, then You must stop using the Product immediately. </div><p></p>
          <div><div className={texts.h007}>1. DEFINITIONS</div> </div><p></p> <div><em>&nbsp; &nbsp; "Company IP"</em> includes, but is not limited to, the contents, layout, design, colours, appearance, graphics and imagery of the Product, Content and Materials as well as all copyrights, trademarks, trade secrets, patents and other intellectual property contained in the Product, Content and Materials. </div><p></p> <div>&nbsp; &nbsp; "Content" means any content, writing, images, audiovisual content or other information published on the Product. </div><p></p> <div>&nbsp; &nbsp; "Contract" means these terms and conditions. </div><p></p> <div>&nbsp; &nbsp; "Dispute" means any dispute, controversy or claim arising out of or in relation to these Terms, including any dispute, controversy or claim relating to the existence, validity or termination of these Terms. </div><p></p> <div>&nbsp; &nbsp; "Effective Date" means the date that these Terms come into force. </div><p></p> <div><em>&nbsp; &nbsp; "Goods"</em> means any or all goods provided by or on the Product. </div><p></p> <div>&nbsp; &nbsp; "Identifying Information" means information provided by You when registering to use the Items, including but not limited to Your name and email address, a user name and a password. </div><p></p>
          <div>&nbsp; &nbsp; "Items" means any and all of the Product, Goods, Services, Content and Materials collectively. </div><p></p> <div><em>&nbsp; &nbsp; "Materials"</em> means any materials, information or documentation that We may provide to You in connection with Your use of the Goods or Services or Product including documentation, data, information developed by Us or owned by Us, and other materials which may assist in Your use of Goods or Services or Product. </div><p></p>
          <div><em>&nbsp; &nbsp; "Parties"</em> means both You (the user of the Product) and Us (the owner of the Product) collectively. </div><p></p> <div>&nbsp; &nbsp; "Product" means including all pages, all sub pages, all blogs, all forums, which is hereinafter referred to as "the Product" and is available at: iTunes &amp; Goggle Play Store </div><p></p>
          <div><em>&nbsp; &nbsp; "Services"</em> means any or all services provided by or on the Product. </div><p></p> <div>&nbsp; &nbsp; "Terms" means these terms and conditions. </div><p></p> <div><em>&nbsp; &nbsp; "Third Party Links" </em>means links or references to websites or applications other than the Product, to content other than the Content or to materials other than the Materials, none of which are controlled by Us. </div><p></p>
          <div>&nbsp; &nbsp; "Us", "We", "Our", "the Company" &nbsp;or "<em>the Owner"</em> refers to Desert Software Pty Ltd </div><p></p> <div>&nbsp; &nbsp; "Us", "We", "Our", "the Company" &nbsp;or "<em>the Owner"</em> also includes any employees, affiliates, agents or other representatives of Desert Software Pty Ltd </div><p></p> <div><em>&nbsp; &nbsp; "You" </em>or <em>"Your"</em> refers to the user of the Product. </div><p></p> <div>&nbsp; &nbsp; "Your Content" means any Content posted to or added to the Product, Content or Materials by You or by somebody authorised by You or doing so on Your behalf. </div><p></p> <div><div className={texts.h007}>2. INTERPRETATION</div> </div><p></p> <div>&nbsp; &nbsp; a. In these Terms, unless the context otherwise requires, the following rules of interpretation shall apply: </div><p></p>
          <div><span className="times-serif" title="Roman numeral">&nbsp; &nbsp; &nbsp; &nbsp; I</span><b><span className="times-serif" title="Roman numeral">.&nbsp;</span></b>Words referring to one gender include every other gender. </div><p></p> <div><span className="times-serif" title="Roman numeral">&nbsp; &nbsp; &nbsp; &nbsp; II</span>. Words referring to a singular number include the plural, and words referring to a plural include the singular. </div><p></p> <div>&nbsp; &nbsp; &nbsp; &nbsp; III. Words referring to a person or persons includes companies, firms, corporations, organisations and vice versa. </div><p></p> <div>&nbsp; &nbsp; &nbsp; &nbsp; IV. Any obligation on a Party not to do something includes an obligation not to allow that thing to be done. </div><p></p>
          <div><div className={texts.h007}>3. YOUR AGREEMENT AND REPRESENTATIONS</div> </div><p></p> <div>&nbsp; &nbsp; a. By continuing to use the Product and the Items You warrant and acknowledge that You have had the chance to review and consider the Terms, that You understand the Terms and that You agree to be bound by the Terms. If You do not understand the Terms or do not agree to be bound by them then you must stop using the Items immediately. We only agree to provide use of the Items to You if You agree to these Terms. </div><p></p> <div>&nbsp; &nbsp; b. By continuing to use the Product and the Items You represent and warrant to Us that You have legal capacity to enter these Terms. </div><p></p> <div>&nbsp; &nbsp; c. By continuing to use the Product and the Items You represent and warrant to Us that You have complied with all of these Terms. </div><p></p>
          <div><div className={texts.h007}>4. AGE RESTRICTION</div> </div><p></p> <div>&nbsp; &nbsp; a. In order to use the Items, you must be aged at least: 6 </div><p></p> <div>&nbsp; &nbsp; b. By using the Items, You represent and warrant that You are aged at least: 6 </div><p></p> <div>&nbsp; &nbsp; c. We accept no responsibility or liability for any misrepresentation of Your age. </div><p></p> <div><div className={texts.h007}>5. LICENCE TO USE PRODUCT, CONTENT AND MATERIALS</div> </div><p></p> <div>&nbsp; &nbsp; a. We may provide You with certain other Items in connection with Your use of the Product. </div><p></p>
          <div>&nbsp; &nbsp; b. Subject to these Terms, We grant You a licence to use the Product, Content and Materials solely in connection with Your use of the Items. The licence created under these Terms is non-exclusive, limited, non-transferable, worldwide and revocable. </div><p></p> <div>&nbsp; &nbsp; c. You may not use the Product, Content or Materials for any purpose other than in accordance with the licence that is provided under this clause, and this licence to use the Product, Content and Materials terminates upon Your cessation of use of the Items or upon termination of this Contract. </div><p></p> <div><div className={texts.h007}>6. SALE OF GOODS/SERVICES</div> </div><p></p> <div>&nbsp; &nbsp; a. We may sell Goods or Services or may allow third parties to sell Goods or Services on the Product. If this occurs, then some specific exclusions of liability will apply, as described in the "Exclusion of Liability" clause. </div><p></p>
          <div>&nbsp; &nbsp; b. Please refer to Our additional terms and conditions for sale of goods and/or terms and conditions for sale of services as applicable. </div><p></p>
          <div><div className={texts.h007}>7. EXCLUSION OF LIABILITY</div> </div><p></p> <div>&nbsp; &nbsp; a. The Product, Content and Materials are provided for general information only and may change at any time without prior notice. </div><p></p>
          <div>&nbsp; &nbsp; b. You accept and acknowledge that the Items may contain mistakes, errors and inaccuracies. </div><p></p> <div>&nbsp; &nbsp; c. Your use of the Product, Content and Materials is entirely at Your risk. It is Your responsibility to make sure that any Goods, Services, Materials, Content or other information available through the Product suits Your particular purpose. </div><p></p> <div>&nbsp; &nbsp; d. Neither We, nor any third parties, provide any guarantees or warranties regarding the accuracy, completeness, performance, reliability, timeliness, quality, merchantability, safety, legality or suitability for a particular purpose of the Items. </div><p></p> <div>&nbsp; &nbsp; e. To the maximum extent permitted by law, We hereby expressly exclude all warranties, guarantees, representations or terms (whether express or implied) except for those expressly set out in these Terms. </div><p></p>
          <div>&nbsp; &nbsp; f. To the maximum extent permitted by law, We hereby expressly exclude any liability in relation to the accuracy, completeness, performance, reliability, timeliness, quality, merchantability, safety, legality or suitability for a particular purpose of the Items. </div><p></p> <div>&nbsp; &nbsp; g. To the maximum extent permitted by law, We hereby expressly exclude any liability in relation to loss of data, interruption to Your business or any damages which are incidental to or arise from such loss of data or interruption to business. </div><p></p>
          <div>&nbsp; &nbsp; h. To the maximum extent permitted by law, We will not be liable for any damage, loss, cost or expense including legal costs and expenses, whether direct or indirect, incurred by You in connection with Your use of the Items. </div><p></p>
          <div>&nbsp; &nbsp; i. for Goods and/or Services sold by third parties via the Product or via Third Party Links (hereinafter "Third Party Goods and Services"): </div><p></p> <div><span className="times-serif" title="Roman numeral">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; I.&nbsp;</span>You acknowledge and agree that We have no control over those Third Party Goods and Services and that You purchase such Third Party Goods and Services at Your own risk. </div><p></p> <div><span className="times-serif" title="Roman numeral">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; II</span>. You acknowledge and agree that We assume no liability and provide no warranties or guarantees regarding the accuracy, completeness, performance, reliability, timeliness, quality, merchantability, safety, legality or suitability for a particular purpose of Third Party Goods and Services. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; III. For any claim You may have against the third party provider of the Third Party Goods and Services (such as the manufacturer or vendor) You agree to pursue that claim directly with that third party provider of the Third Party Goods and Services and not with Us. </div><p></p> <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; IV. To the maximum extent permitted by law, You hereby release Us from any claim related to Third Party Goods and Services including any and all warranty and product liability claims. </div><p></p>
          <div><div className={texts.h007}>8. DELIVERY</div> </div><p></p> <div>&nbsp; &nbsp; a. We may arrange delivery of Physical Goods by courier or by Australia Post. We process deliveries promptly upon receipt of full payment. </div><p></p> <div>&nbsp; &nbsp; b. Delivery of physical Goods within Australia may take: "two (2) to fourteen (14) business days. </div><p></p> <div>&nbsp; &nbsp; c. Delivery of physical Goods outside of Australia may take: between 7 &amp; 21 Days </div><p></p> <div>&nbsp; &nbsp; d. Any digital Goods are delivered immediately. You acknowledge and accept that there are inherent risks with downloading any digital Goods. Please contact Us using the details at the end of these Terms if You experience technical problems regarding delivery of digital Goods. </div><p></p>
          <div>&nbsp; &nbsp; e. We take no responsibility for Goods that are lost or damaged during delivery. </div><p></p> <div>&nbsp; &nbsp; f. We may choose in Our sole discretion whether or not to replace Goods which are lost or damaged during delivery. </div><p></p> <div>&nbsp; &nbsp; g. Any disputes regarding physical Goods which are lost or damaged during delivery should be directly taken up with the relevant courier company or with Australia Post as applicable. </div><p></p> <div><div className={texts.h007}>9. RETURNS/REFUNDS/REPAIRS</div> </div><p></p> <div>&nbsp; &nbsp; a. We handle returns, refunds and repairs in accordance with Our obligations under the Australian Consumer Law. </div><p></p>
          <div>&nbsp; &nbsp; b. If You are seeking a return, refund or repair, You may contact Us using the details at the end of these Terms. In order for your request to be handled promptly, please provide full details about Your valid reason for return, refund or repair. </div><p></p> <div><div className={texts.h007}>10. NO PROFESSIONAL ADVICE</div> </div><p></p> <div>&nbsp; &nbsp; a. The information provided through the Product, Content, Materials or through the other Items is for information purposes only. It does not address Your specific circumstances. It is not professional advice. </div><p></p> <div>&nbsp; &nbsp; b. You acknowledge and agree that any information provided on the Product, Content, Materials or through the other Items is not professional advice, whether legal, accounting, medical, financial or other professional advice. </div><p></p> <div>&nbsp; &nbsp; c. You acknowledge and agree that no fiduciary relationship has been created between Us and You. </div><p></p>
          <div>&nbsp; &nbsp; d. You acknowledge and agree that Your use of the Product and Items is at Your own risk. We do not assume responsibility or liability for any information provided through the Product or other Items. </div><p></p>
          <div>&nbsp; &nbsp; e. You acknowledge and agree that it is Your responsibility to evaluate all information that is provided through the Product or other Items in consultation with Your own professional adviser or advisers as appropriate. </div><p></p> <div><div className={texts.h007}>11. INDEMNITY</div> </div><p></p> <div>&nbsp; &nbsp; You hereby indemnify Us (which, for the sake of clarity, also includes any of Our employees, affiliates, agents or other representatives) and You agree to defend Us and to hold Us harmless in relation to any and all claims, suits, demands, actions, liabilities, costs and expenses (including legal costs and expenses on a full indemnity basis) which may arise from or relate to Your use or misuse of the Items. You agree that We may select Our own legal representation and may participate in Our own legal proceedings if We choose. </div><p></p>
          <div><div className={texts.h007}>12. TERMINATION</div> </div><p></p> <div>&nbsp; &nbsp; a. We may immediately terminate these Terms at any time, with or without cause. </div><p></p> <div>&nbsp; &nbsp; b. We specifically reserve the right to terminate these Terms if You breach these Terms in any way. </div><p></p> <div>&nbsp; &nbsp; c. These Terms terminate automatically if we cease to operate the Product for any reason. </div><p></p>
          <div>&nbsp; &nbsp; d. If You have registered for an account with Us, You may terminate these Terms at any time by contacting Us and requesting termination. </div><p></p>
          <div>&nbsp; &nbsp; e. At the termination of these Terms, any provisions which would by their nature be expected to survive termination shall remain in full force and effect, including but not limited to Our exclusions of liability as outlined in the "Exclusions of Liability" clause. </div><p></p> <div><div className={texts.h007}>13. OTHER ACTION</div> </div><p></p>
          <div>&nbsp; &nbsp; a. We reserve the right to take any of the following actions in Our sole discretion: </div><p></p>
          <div><span className="times-serif" title="Roman numeral">&nbsp; &nbsp; &nbsp; &nbsp; I. </span>
            Monitor, review, edit or delete any Content which You have added, uploaded or posted to the Product or through the other Items, whether or not You have breached these Terms. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; II. Record any correspondence that occurs in public sections of the Product. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; III. Review any allegations about breaches of these Terms, and determine in Our sole discretion whether to take any action in response to those alleged breaches, including removal of any Content in relation to those alleged breaches. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; IV. Determine in Our sole discretion whether to terminate Your or another Product user's access to any particular section or sections of the Product or other Items. </div><p></p> <div><div className={texts.h007}>14. ACCEPTABLE USE</div> </div><p></p>
          <div>&nbsp; &nbsp; a. You agree not to use the Product or the Items for any unlawful purpose or any purpose prohibited under this clause. You agree not to use the Product or the Items in any way that could damage the Product, the Items, or Our general business. </div><p></p>
          <div>&nbsp; &nbsp; b. You further agree not to use the Product or the Items: </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; I. to harass, abuse, or threaten any other person or to otherwise violate any other person's legal rights; </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; II. to violate any intellectual property rights of Us or of any third party; </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; III. to upload or otherwise disseminate any computer viruses or other software that may damage the property of another; </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; IV. to commit any kind of fraud; </div><p></p> <div>&nbsp; &nbsp; &nbsp; &nbsp; V. to engage in or create any unlawful gambling, sweepstakes or pyramid schemes; </div><p></p> <div>&nbsp; &nbsp; &nbsp; &nbsp; VI. to publish or distribute any obscene or defamatory material; </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; VII. to publish or distribute any material that incites violence, hatred or discrimination towards any person, group or community; </div><p></p> <div>&nbsp; &nbsp; &nbsp; &nbsp; VIII. to unlawfully gather information about others. </div><p></p>
          <div>&nbsp; &nbsp; c. Unauthorised use by You of the Items may be a criminal offence and may give rise to a claim for damages. </div><p></p>
          <div><div className={texts.h007}>15. VARIATION OF TERMS</div> </div><p></p>
          <div>&nbsp; &nbsp; a. You hereby acknowledge and agree that these Terms may be varied or amended from time to time in Our sole discretion. If You continue to use the Product following any such variation or amendment You will be deemed to have confirmed and agreed to the new Terms as varied or amended. </div><p></p>
          <div>&nbsp; &nbsp; b. You agree to routinely monitor these Terms and to refer to the Effective Date posted at the top of these Terms in order to monitor any modifications or variations. You further agree to clear Your cache when doing so in order to avoid accessing a prior version of these Terms. </div><p></p>
          <div>&nbsp; &nbsp; c. In the event that You fail to monitor any modifications to or variations of these Terms, You agree that such failure shall be considered an affirmative waiver of Your right to review the modified or varied Terms. </div><p></p> <div><div className={texts.h007}>16. THIRD PARTY LINKS</div> </div><p></p>
          <div>&nbsp; &nbsp; a. You hereby acknowledge that We may from time to time include links or references to other websites, other content or other materials (hereinafter "Third Party Links"), none of which are controlled by Us. </div><p></p>
          <div>&nbsp; &nbsp; b. You hereby acknowledge that these Third Party Links are provided for Your information only and that We do not make any representations, warranties or guarantees as to the accuracy, completeness, performance, reliability, timeliness, quality or suitability for a particular purpose of these Third Party Links. We do not endorse, approve or support these Third Party Links. You use the Third Party Links at Your own risk. </div><p></p>
          <div><div className={texts.h007}>17. AFFILIATE MARKETING AND ADVERTISING</div> </div><p></p>
          <div>&nbsp; &nbsp; a. Through the Product and other Items, We may engage in affiliate marketing whereby We receive a commission on or a percentage of proceeds of sales of Third Party Goods and Services that occur through Our Product and other Items. </div><p></p>
          <div>&nbsp; &nbsp; b. Through the Product and other Items, We may accept advertising and sponsorships from commercial businesses whereby third parties pay us to advertise on the Product or through Our other Items, or we may receive other forms of advertising compensation. </div><p></p>
          <div><div className={texts.h007}>18. CHANGES TO PRODUCT</div> </div><p></p>
          <div>&nbsp; &nbsp; a. You acknowledge and agree that We may, in Our sole discretion, vary, alter, amend, change or update the Content, Materials or the Product at any time. </div><p></p>
          <div>&nbsp; &nbsp; b. You acknowledge, agree and accept that the Product may be unavailable from time to time (whether it is unavailable due to maintenance or for any other reason). </div><p></p>
          <div>&nbsp; &nbsp; c. You acknowledge, agree and accept that We take no responsibility for, and to the maximum extent permitted by law we shall not be liable in any way for the Items being temporarily unavailable, whether due to reasons within our control or not. </div><p></p>
          <div><div className={texts.h007}>19. INTELLECTUAL PROPERTY</div> </div><p></p>
          <div>&nbsp; &nbsp; a. The Items contain intellectual property that is owned by Us and/or th at is licensed to Us. This includes, but is not limited to, the contents, layout, design, colours, appearance, graphics and imagery of the Product, Content, Materials and Goods as well as all copyrights, trademarks, trade secrets, patents and other intellectual property contained in the Items (he reinafter "Company IP"). </div><p></p> 
          <div>&nbsp; &nbsp; b. You hereby acknowledge and agree that, as between Us and You, We own all intellectual property rights in the Items and that nothing in these Terms amounts to a transfer of any intellectual property rights from Us to You. </div><p></p>
          <div>&nbsp; &nbsp; c. You hereby ackn owledge and agree not to use the Company IP for any unlawful or infringing purpose. </div><p></p>
          <div>&nbsp; &nbsp; d. You hereby acknowledge and agree not to reprodu ce or distribute the Company IP in any way, including electronically or via registration of any new trademarks, trade names, service marks or Uniform Reso urce Locators (URLs) without express written permission from Us. </div><p></p>
          <div>&nbsp; &nbsp; e. You hereby acknowledge and agree that by adding, posting or uploadi ng any Content on the Product (hereinafter "Your Content"), you grant Us a worldwide, irrevocable, perpetual, non-exclusive, royalty-free and transferable r ight and licence to use Your Content in any way We choose. This licence includes a right and licence to: </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; I. reproduce, cop y, alter or make derivate works from Your Content in any way We choose; and </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; II. display, communicate to the public, broadca st or transmit Your Content in any way We choose; and </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; III. authorise any other person, company or organisation to use Your C ontent in any way We choose. </div><p></p>
          <div>&nbsp; &nbsp; f. You represent and warrant to Us that You have all necessary rights to grant the licences and to provide th e consents set out in this clause in relation to "Intellectual property". </div><p></p>
          <div>&nbsp; &nbsp; g. All of the provisions of this clause in relation to "Intellect ual property" shall survive any termination of these Terms. </div><p></p>
          <div><div className={texts.h007}>20. USER REGISTRATION</div> </div><p></p>
          <div>&nbsp; &nbsp; a. You may be asked to register with Us in order to use or access the Items. </div><p></p>
          <div>&nbsp; &nbsp; b. If You register with Us, You may be asked to provide personal details such as Your name and email address, as well as choosing a user name and a password ("Identifying Information"). This Identifying Information will allow You to access the Items. </div><p></p>
          <div>&nbsp; &nbsp; c. You acknowledge that You are responsible for ensuring the accuracy of any Identifying Information You provide as part of the registration pr ocess. </div><p></p> <div>&nbsp; &nbsp; d. You agree that You will not share your Identifying Information with any third party and if You discover that Your Identifying Inf ormation has been compromised, You agree to notify Us immediately in writing. </div><p></p>
          <div>&nbsp; &nbsp; e. You acknowledge that You are responsible for maintaining the safety and security of Your Identifying Information as well as keeping Us informed of any changes to Your Identifying Information. </div><p></p>
          <div>&nbsp; &nbsp; f. You ack nowledge that providing false or misleading information, or using the Items to further fraud or unlawful activity is grounds for immediate termination of these T erms. </div><p></p>
          <div><div className={texts.h007}>21. PRIVACY</div> </div><p></p>
          <div>&nbsp; &nbsp; a. Through Your use of the Product or other Items, You may provide Us with some of Your personal in formation. By using the Product or Items, You authorise Us to use Your information in Australia and any other country where We operate. </div><p></p>
          <div>&nbsp; &nbsp; b. W e take Our privacy obligations very seriously. </div><p></p>
          <div>&nbsp; &nbsp; c. Please refer to Our privacy policy for further information about what information We collec t, how We use it and store it, and Your rights in relation to it. </div><p></p>
          <div><div className={texts.h007}>22. REVERSE ENGINEERING AND SECURITY</div> </div><p></p>
          <div>&nbsp; &nbsp; You agree not to: </div><p></p> <div>&nbsp; &nbsp; a. reverse engineer, or attempt to reverse engineer or disassemble any code or software from or on the Items; and </div><p></p>
          <div>&nbsp; &nbsp; b . violate the security of the Items through any unauthorised access, circumvention of encryption or other security tools, data mining or interference with any h ost, user or network. </div><p></p> <div><div className={texts.h007}>23. SPAM POLICY</div> </div><p></p>
          <div>&nbsp; &nbsp; You are prohibited from using the Items for the purpose of gathering email addr esses and/or personal information from people, companies or other organisations and/or for sending bulk emails or unsolicited emails. </div><p></p> <div><div className={texts.h007}>24. GENERAL P ROVISIONS</div> </div><p></p>
          <div>&nbsp; &nbsp; a.<span className={texts.h007}> Australian Consumer Law:</span> You may have certain rights, warranties, guarantees and remedies under the
                        <em>Australian Consumer Law</em>, which is contained in the <em>Competition and Consumer Act 2010 (Cth),</em> and these rights, warranties, guarantees and remedies may not be restricted, modified or excluded by Us. Our liability to you is governed solely by these Terms and the <em>Australian Consumer Law.</em> </div><p></p>
          <div>&nbsp; &nbsp; b. <span className={texts.h007}>Applicable law:</span> Your use of the Product and the Items is subject to the laws of Victoria and each party submits to the jur isdiction of the courts of Victoria. </div><p></p>
          <div>&nbsp; &nbsp; c. <span className={texts.h007}>Written communication:</span> In relation to any correspondence or notification which i s required under these Terms to be provided in writing from one party to the other party: </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; I. such notice is properly given if given to the other party: </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A. by email to an email address that the other party has nominated, acknowledged or use d in connection with the use of the Product or other Items. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; B. by facsimile to a facsimile address which the oth er party has nominated, acknowledged or used in connection with the use of the Product or other Items. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; C. by pos t to a postal address the other party has nominated, acknowledged or used in connection with the use of the Product or other Items. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; II. such notice is taken to be received: </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A. if sent by email, when the ema il becomes capable of being retrieved by the recipient at the relevant email address. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; B. if sent by facs imile, at the time shown of correct and complete transmission to the recipient's facsimile number by the sending machine. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; C. if sent by prepaid post within Australia, five (5) days after the date of posting. </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; D. if sent by prepaid post to or from an address outside Australia, twenty one (21) days after the date of posting. </div><p></p>
          <div>&nbsp; &nbsp; d.<span className={texts.h007}> No assignment: </span>You must not assign, sub-licence or otherwise deal in any way with your rights under these Terms without Our prior written consent. </div><p></p>
          <div>&nbsp; &nbsp; e. <span className={texts.h007}>Severability:</span> If any clause or sub-clause of these Terms is held to be invalid or unenf orceable, it is to be read down or severed such that the remaining clauses and sub-clauses will be enforced to the maximum extent possible. In such circumst ances, the remainder of these Terms shall continue in full force and effect. </div><p></p>
          <div>&nbsp; &nbsp; f. <span className={texts.h007}>No waiver: </span>In the event that We fail to enforce any provision of these Terms, this shall not constitute a waiver of any future enforcement of that provision or of any other provision. Waiver of any clause or sub-clause of these Terms will not constitute a waiver of any other clause or sub-clause. </div><p></p>
          <div>&nbsp; &nbsp; g. <span className={texts.h007}>Headings for convenience only: </span>Headings of clauses and sub-clauses under these Terms are for convenience only. Headings shall not affect the meaning of any provision of these Terms. </div><p></p>
          <div>&nbsp; &nbsp; h.
                        <span className={texts.h007}>Parties must take all reasonable steps: </span>Each party must, at its own expense, take all reasonable steps and do a ll that is reasonably necessary to give full effect to these Terms and the events contemplated by them. </div><p></p>
          <div>&nbsp; &nbsp; i.
                        <span className={texts.h007}>Separate agreements:</span> You may have other legal agreements with Us. Those other legal agreements are separate from and are in addition to these Terms. These Terms do not alter, amend, revise or replace the terms of any other legal agreements You may have with Us. </div><p></p>
          <div><div className={texts.h007}>25. CONTACT US</div> </div><p></p>
          <div>&nbsp; &nbsp; You can contact us about these Terms using the following details: </div><p></p>
          <div>&nbsp; &nbsp; &nbsp; &nbsp; Desert Software Pty Ltd<p></p> &nbsp; &nbsp; &nbsp; &nbsp; (03)9759 6266<p></p> &nbsp; &nbsp; &nbsp; &nbsp; info@desertsoftware.com.au </div><br /><br />


        </div>
      </div>
    </div>
  );
}